name: "Terraform Plan"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-plan.yml"

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.PAT }}
          workflow: react-deploy.yml
          name: react-build
          path: ./frontend/dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        id: terraform-init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        id: terraform-plan
        working-directory: ./terraform
        run: terraform plan
