name: "Terraform Destroy"

on:
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.10.5"

    - name: Terraform Init
      id: terraform-init
      working-directory: ./terraform
      run: terraform init
    
    - name: Terraform Plan Destroy
      id: terraform-plan-destroy
      working-directory: ./terraform
      run: terraform plan -destroy
    
    - name: Manual Workflow Approval
      uses: trstringer/manual-approval@v1.9.1
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: placy2
        issue_title: "Confirm Terraform Destroy"
        issue_message: "Confirm the plan to destroy the Terraform resources looks good and the destroy action should be applied."

    - name: Terraform Destroy
      working-directory: ./terraform
      run: terraform destroy -auto-approve